const axios = require('axios');
const fs = require('fs');
const qs = require('qs');

module.exports = {
    name: 'admit',
    aliases: ['jnvu'],
    category: 'general',
    description: 'Download JNVU Admit Card',
    usage: '.admit [form_number]',

    async execute(sock, msg, args, extra) {
        // extra.reply का इस्तेमाल करके रिप्लाई देना आसान है
        try {
            const formNumber = args[0];

            if (!formNumber) {
                return await extra.reply("❌ कृपया फॉर्म नंबर दें।\nउदाहरण: `.admit 12880707` ");
            }

            await extra.reply(`🔍 फॉर्म नंबर ${formNumber} के लिए एडमिट कार्ड ढूंढ रहा हूँ...`);

            const postData = qs.stringify({
                '__EVENTTARGET': '',
                '__EVENTARGUMENT': '',
                'txtchallanNo': formNumber.trim(),
                'btnGetResult': 'Download'
            });

            const response = await axios({
                method: 'post',
                url: 'https://erp.jnvuiums.in/Exam/Pre_Exam/Exam_ForALL_AdmitCard.aspx',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'
                },
                data: postData,
                responseType: 'arraybuffer',
                timeout: 30000 
            });

            // PDF Validation
            if (response.data.length < 2500) {
                return await extra.reply("❌ एडमिट कार्ड नहीं मिला। शायद फॉर्म नंबर गलत है या अभी अपलोड नहीं हुआ।");
            }

            const path = `./${formNumber}.pdf`;
            fs.writeFileSync(path, response.data);

            // sock.sendMessage का सही इस्तेमाल (जैसा ping.js में है)
            await sock.sendMessage(extra.from, { 
                document: fs.readFileSync(path), 
                mimetype: 'application/pdf', 
                fileName: `JNVU_AdmitCard_${formNumber}.pdf`,
                caption: `✅ *JNVU Admit Card*\n🔹 Form No: ${formNumber}\n\n_Generated by Knight Bot_`
            }, { quoted: msg });

            // Cleanup
            if (fs.existsSync(path)) fs.unlinkSync(path);

        } catch (err) {
            console.error("Admit Command Error:", err.message);
            await extra.reply("❌ सर्वर एरर आया है या वेबसाइट रिस्पॉन्स नहीं दे रही।");
        }
    }
};
