const axios = require('axios');
const fs = require('fs');
const qs = require('qs');

module.exports = {
    name: 'admit',
    alias: ['jnvu'],
    category: 'general',
    async execute(m, { conn, text }) {
        // m.reply की जगह इस्तेमाल होने वाला फंक्शन
        const sendReply = (txt) => conn.sendMessage(m.chat, { text: txt }, { quoted: m });

        try {
            const formNumber = text ? text.trim() : null;

            if (!formNumber) {
                return sendReply("❌ कृपया फॉर्म नंबर दें।\nउदाहरण: `.admit 12880707` ");
            }

            await sendReply(`🔍 फॉर्म नंबर ${formNumber} के लिए एडमिट कार्ड ढूंढ रहा हूँ...`);

            // POST Data (Website elements)
            const postData = qs.stringify({
                '__EVENTTARGET': '',
                '__EVENTARGUMENT': '',
                'txtchallanNo': formNumber,
                'btnGetResult': 'Download'
            });

            const response = await axios({
                method: 'post',
                url: 'https://erp.jnvuiums.in/Exam/Pre_Exam/Exam_ForALL_AdmitCard.aspx',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'
                },
                data: postData,
                responseType: 'arraybuffer',
                timeout: 30000 // 30 seconds timeout
            });

            // Check if it's a valid PDF
            if (response.data.length < 2500) {
                return sendReply("❌ एडमिट कार्ड नहीं मिला। शायद फॉर्म नंबर गलत है या वेबसाइट रिस्पॉन्स नहीं दे रही।");
            }

            const path = `./${formNumber}.pdf`;
            fs.writeFileSync(path, response.data);

            // Sending the PDF file
            await conn.sendMessage(m.chat, { 
                document: fs.readFileSync(path), 
                mimetype: 'application/pdf', 
                fileName: `JNVU_AdmitCard_${formNumber}.pdf`,
                caption: `✅ *JNVU Admit Card*\n🔹 Form No: ${formNumber}\n\n_Generated by Knight Bot_`
            }, { quoted: m });

            // Cleanup
            if (fs.existsSync(path)) fs.unlinkSync(path);

        } catch (err) {
            console.error("Admit Command Error:", err.message);
            sendReply("❌ सर्वर डाउन है या फॉर्म नंबर इनवैलिड है। कृपया थोड़ी देर बाद प्रयास करें।");
        }
    }
};
